# Generated by Django 5.2.1 on 2025-06-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_id',
            new_name='shipping',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shippingdetails',
            old_name='address_id',
            new_name='address',
        ),
    ]
