# Generated by Django 4.2.23 on 2025-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Admin', 'Admin')], default='Cliente', max_length=50, null=True),
        ),
    ]
